name: Deploy to Surge.sh

on:
  push:
    branches:
      - main  # Cambia esto si tu branch se llama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge.sh
      run: surge ./ https://wicked-expansion.surge.sh
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # Asegúrate de que SURGE_TOKEN está configurado

